In [11]:
# installing kaggle library
! pip install kaggle
! pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\annie\appdata\roaming\python\python311\site-packages (2.2.3)
Requirement already satisfied: bleach in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (0.1.34)
Requirement already satisfied: packaging in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (7.35.1)
Requirement already satisfied: python-dateutil in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\annie\appdata\roaming\python\python311\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\annie\appdata\roaming\python\python311\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\annie\appdata\roaming\python\python311\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kaggle) (2025.10.5)
Requirement already satisfied: colorama in c:\users\annie\appdata\roaming\python\python311\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in c:\users\annie\appdata\roaming\python\python311\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (0.1.34)
Requirement already satisfied: packaging in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.35.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (2025.10.5)
Requirement already satisfied: colorama in c:\users\annie\appdata\roaming\python\python311\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import kagglehub
import shutil
import os

# 1. Download the latest version to the default cache
cache_path = kagglehub.dataset_download("kazanova/sentiment140")
print("Downloaded to cache at:", cache_path)

# 2. Define your specific destination folder
target_folder = "."

# 3. Copy the contents from the cache to your target folder
shutil.copytree(cache_path, target_folder, dirs_exist_ok=True)

print(f"Dataset is now ready directly in: {target_folder}")

C:\Users\Annie\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloaded to cache at: C:\Users\Annie\.cache\kagglehub\datasets\kazanova\sentiment140\versions\2
Dataset is now ready directly in: .

In [2]:
# importing the inpendencies
import numpy as np
import pandas as pd
import re # regular expression, pattern matching
from nltk.corpus import stopwords # natural language toolkit
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer # turn text into number - a matrix of TF-IDF features
from sklearn.model_selection import train_test_split # split the dataset into training and testing sets
from sklearn.linear_model import LogisticRegression # machine learning model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # evaluate the model

In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Annie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
# printing the stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [22]:
# data processing
# loading the dataset
twitter_data = pd.read_csv('training.1600000.processed.noemoticon.csv', encoding = 'ISO-8859-1')

In [23]:
# checking the dataset
twitter_data.shape

(1599999, 6)

In [24]:
# checking the first few rows of the dataset
twitter_data.head()

   0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D
0  0  ...  is upset that he can't update his Facebook by ...
1  0  ...  @Kenichan I dived many times for the ball. Man...
2  0  ...    my whole body feels itchy and like its on fire
3  0  ...  @nationwideclass no, it's not behaving at all....
4  0  ...                      @Kwesidei not the whole crew

[5 rows x 6 columns]

In [25]:
# naming the columns
column_names = ['target', 'id', 'date', 'flag', 'user', 'text']
twitter_data = pd.read_csv('training.1600000.processed.noemoticon.csv', names=column_names, encoding = 'ISO-8859-1')
twitter_data.head()

   target  ...                                               text
0       0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1       0  ...  is upset that he can't update his Facebook by ...
2       0  ...  @Kenichan I dived many times for the ball. Man...
3       0  ...    my whole body feels itchy and like its on fire
4       0  ...  @nationwideclass no, it's not behaving at all....

[5 rows x 6 columns]