In [11]:
# installing kaggle library
! pip install kaggle
! pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\annie\appdata\roaming\python\python311\site-packages (2.2.3)
Requirement already satisfied: bleach in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (0.1.34)
Requirement already satisfied: packaging in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (7.35.1)
Requirement already satisfied: python-dateutil in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\annie\appdata\roaming\python\python311\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\annie\appdata\roaming\python\python311\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\annie\appdata\roaming\python\python311\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kaggle) (2025.10.5)
Requirement already satisfied: colorama in c:\users\annie\appdata\roaming\python\python311\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in c:\users\annie\appdata\roaming\python\python311\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (0.1.34)
Requirement already satisfied: packaging in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\annie\appdata\roaming\python\python311\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.35.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\annie\appdata\roaming\python\python311\site-packages (from requests->kagglehub) (2025.10.5)
Requirement already satisfied: colorama in c:\users\annie\appdata\roaming\python\python311\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import kagglehub
import shutil
import os

# 1. Download the latest version to the default cache
cache_path = kagglehub.dataset_download("kazanova/sentiment140")
print("Downloaded to cache at:", cache_path)

# 2. Define your specific destination folder
target_folder = "."

# 3. Copy the contents from the cache to your target folder
shutil.copytree(cache_path, target_folder, dirs_exist_ok=True)

print(f"Dataset is now ready directly in: {target_folder}")

C:\Users\Annie\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloaded to cache at: C:\Users\Annie\.cache\kagglehub\datasets\kazanova\sentiment140\versions\2
Dataset is now ready directly in: .

In [2]:
# importing the inpendencies
import numpy as np
import pandas as pd
import re # regular expression, pattern matching
from nltk.corpus import stopwords # natural language toolkit
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer # turn text into number - a matrix of TF-IDF features
from sklearn.model_selection import train_test_split # split the dataset into training and testing sets
from sklearn.linear_model import LogisticRegression # machine learning model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # evaluate the model

In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Annie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
# printing the stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [5]:
# data processing
# loading the dataset
twitter_data = pd.read_csv('training.1600000.processed.noemoticon.csv', encoding = 'ISO-8859-1')

In [6]:
# checking the dataset
twitter_data.shape

(1599999, 6)

In [7]:
# checking the first few rows of the dataset
twitter_data.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [8]:
# naming the columns
column_names = ['target', 'id', 'date', 'flag', 'user', 'text']
twitter_data = pd.read_csv('training.1600000.processed.noemoticon.csv', names=column_names, encoding = 'ISO-8859-1')
twitter_data.head()

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [9]:
# counting the number of missing values
twitter_data.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [10]:
# counting the number of positive and negative tweets
twitter_data['target'].value_counts()

target
0    800000
4    800000
Name: count, dtype: int64

In [11]:
# convert the target column to binary values
twitter_data.replace({'target':{4:1}}, inplace=True)
twitter_data['target'].value_counts()

target
0    800000
1    800000
Name: count, dtype: int64

In [12]:
# stemming: reducing words to their root form
port_stem = PorterStemmer()

In [ ]:
# loading the stopwords once and using it in the stemming function to avoid loading it multiple times
stop_words = set(stopwords.words('english'))

# defining a pattern to remove all the special characters and numbers
pattern = re.compile('[^a-zA-Z]')

def stemming(content):
    stemmed_content = pattern.sub(' ', content) # removing all the special characters and numbers
    stemmed_content = stemmed_content.lower() # converting all the characters to lower case
    stemmed_content = stemmed_content.split() # splitting the content into individual words
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stop_words] # stemming the words and removing the stopwords
    stemmed_content = ' '.join(stemmed_content) # joining the words back into a single string
    return stemmed_content

In [16]:
twitter_data['stemmed_content'] = twitter_data['text'].apply(stemming)

In [17]:
twitter_data.head()

,target,id,date,flag,user,text,stemmed_content
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",switchfoot http twitpic com zl awww bummer sho...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,upset updat facebook text might cri result sch...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,kenichan dive mani time ball manag save rest g...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,whole bodi feel itchi like fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",nationwideclass behav mad see

In [18]:
# seperating the data and lable
X = twitter_data['stemmed_content'].values
Y = twitter_data['target'].values
print(X, Y)

['switchfoot http twitpic com zl awww bummer shoulda got david carr third day'
 'upset updat facebook text might cri result school today also blah'
 'kenichan dive mani time ball manag save rest go bound' ...
 'readi mojo makeov ask detail'
 'happi th birthday boo alll time tupac amaru shakur'
 'happi charitytuesday thenspcc sparkschar speakinguph h'] [0 0 0 ... 1 1 1]

In [19]:
# splitting the dataset into training and testing sets
# stratify=Y is used to ensure that the distribution of the target variable is similar in both the training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [20]:
print(X.shape, X_train.shape, X_test.shape)

(1600000,) (1280000,) (320000,)

In [21]:
# converting the text data into numerical data using TF-IDF vectorizer
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train) # fitting the vectorizer on the training data and transforming it into score, understanding the nature of data
X_test = vectorizer.transform(X_test) # transforming the testing data into a matrix of TF-IDF features using the fitted vectorizer,

In [ ]:
print(X_train)
# Coords (Row, Column) : Row is the index of the sample in the dataset, Column is the index assigned to a specific word in TF-IDF vocabulary
# Values : The actual TF-IDF score for the word in that specific sample, indicating its importance in the context of the document and the entire corpus
# e.g. 0.27259876... is the importance score for word #436,713 in tweet #0

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9453092 stored elements and shape (1280000, 461488)>
  Coords	Values
  (0, 436713)	0.27259876264838384
  (0, 354543)	0.3588091611460021
  (0, 185193)	0.5277679060576009
  (0, 109306)	0.3753708587402299
  (0, 235045)	0.41996827700291095
  (0, 443066)	0.4484755317023172
  (1, 160636)	1.0
  (2, 109306)	0.4591176413728317
  (2, 124484)	0.1892155960801415
  (2, 407301)	0.18709338684973031
  (2, 129411)	0.29074192727957143
  (2, 406399)	0.32105459490875526
  (2, 433560)	0.3296595898028565
  (2, 77929)	0.31284080750346344
  (2, 443430)	0.3348599670252845
  (2, 266729)	0.24123230668976975
  (2, 409143)	0.15169282335109835
  (2, 178061)	0.1619010109445149
  (2, 150715)	0.18803850583207948
  (2, 132311)	0.2028971570399794
  (2, 288470)	0.16786949597862733
  (3, 406399)	0.29029991238662284
  (3, 158711)	0.4456939372299574
  (3, 151770)	0.278559647704793
  (3, 56476)	0.5200465453608686
  :	:
  (1279996, 318303)	0.21254698865277744
  (1279996, 434014)	0.27189450523324465
  (1279996, 390130)	0.2206474219107611
  (1279996, 373144)	0.35212500999832036
  (1279996, 238077)	0.5249170684084672
  (1279996, 238078)	0.5606696159563151
  (1279997, 5685)	0.48650358607431304
  (1279997, 273084)	0.4353549002982409
  (1279997, 112591)	0.7574829183045267
  (1279998, 412553)	0.2816582375021589
  (1279998, 93795)	0.21717768937055476
  (1279998, 169461)	0.2659980990397061
  (1279998, 124765)	0.32241752985927996
  (1279998, 435463)	0.2851807874350361
  (1279998, 153281)	0.28378968751027456
  (1279998, 156297)	0.3137096161546449
  (1279998, 162047)	0.34691726958159064
  (1279998, 275288)	0.38703346602729577
  (1279998, 385313)	0.4103285865588191
  (1279999, 242268)	0.19572649660865402
  (1279999, 31410)	0.248792678366695
  (1279999, 435572)	0.31691096877786484
  (1279999, 433612)	0.3607341026233411
  (1279999, 135384)	0.6130934129868719
  (1279999, 96224)	0.5416162421321443

In [24]:
print(X_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2289192 stored elements and shape (320000, 461488)>
  Coords	Values
  (0, 15110)	0.1719352837797837
  (0, 31168)	0.1624772418052177
  (0, 67828)	0.26800375270827315
  (0, 106069)	0.36555450010904555
  (0, 132364)	0.255254889555786
  (0, 138164)	0.23688292264071406
  (0, 171378)	0.2805816206356074
  (0, 271016)	0.45356623916588285
  (0, 279082)	0.17825180109103442
  (0, 388348)	0.2198507607206174
  (0, 398906)	0.34910438732642673
  (0, 409143)	0.3143047059807971
  (0, 420984)	0.17915624523539805
  (1, 6463)	0.30733520460524466
  (1, 15110)	0.211037449588008
  (1, 145393)	0.575262969264869
  (1, 217562)	0.40288153995289894
  (1, 256777)	0.28751585696559306
  (1, 348135)	0.4739279595416274
  (1, 366203)	0.24595562404108307
  (2, 22532)	0.3532582957477176
  (2, 34401)	0.37916255084357414
  (2, 89448)	0.36340369428387626
  (2, 183312)	0.5892069252021465
  (2, 256834)	0.2564939661498776
  :	:
  (319994, 443794)	0.2782185641032538
  (319995, 107868)	0.33399349737546963
  (319995, 109379)	0.3020896484890833
  (319995, 155493)	0.2770682832971669
  (319995, 213324)	0.2683969144317079
  (319995, 232891)	0.2574127854589077
  (319995, 296662)	0.3992485679384015
  (319995, 315813)	0.2848229914563413
  (319995, 324496)	0.36131679336475747
  (319995, 416257)	0.23816465111736282
  (319995, 420984)	0.22631428606830148
  (319995, 444934)	0.32110928175992615
  (319996, 397506)	0.9101400928717545
  (319996, 438709)	0.4143006291901984
  (319997, 98792)	0.4463892055808332
  (319997, 169411)	0.403381646999604
  (319997, 261286)	0.37323893626855326
  (319997, 288421)	0.48498483387153407
  (319997, 349904)	0.32484594100566083
  (319997, 416695)	0.29458327588067873
  (319997, 444770)	0.2668297951055569
  (319998, 130192)	0.6941927210956169
  (319998, 438748)	0.719789181620468
  (319999, 389755)	0.9577980203954275
  (319999, 400636)	0.2874420848216212

In [27]:
# training the model - logistic regression
model = LogisticRegression(max_iter=1000) # max_iter=1000 is used to increase the number of iterations for convergence, as the default value of 100 may not be sufficient for some datasets

In [28]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [29]:
# model evaluation
# accuracy score on the training data
X_train_prediction = model.predict(X_train) # predicting the target variable for the training data using the trained model
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.79871953125

In [30]:
# model evaluation
# accuracy score on the test data
X_test_prediction = model.predict(X_test) # predicting the target variable for the test data using the trained model
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.77668125

Note: If the accuracy score of training data is high and that of test set is low, the model is overfitted

In [31]:
# saving the trained model and vectorizer using pickle
import pickle

In [32]:
filename = 'trained_model.sav'
pickle.dump(model, open(filename, 'wb')) # saving the trained model

In [34]:
# using the saved model to make predictions on new data
# loading the saved model
loaded_model = pickle.load(open('trained_model.sav', 'rb'))

In [40]:
X_new = X_test[200]
print(Y_test[200])
prediction = model.predict(X_new)
print(prediction)

1
[1]

In [36]:
if prediction[0] == 1:
    print("Positive")
else:
    print("Negative")

Positive

In [43]:
pickle.dump(vectorizer, open('vectorizer.sav', 'wb')) # saving the vectorizer